# Generated by Django 5.1.1 on 2024-09-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watch_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
