# Generated by Django 5.1.1 on 2024-09-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image_file',
            field=models.ImageField(default=1, upload_to='playlist_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Public', 'Public')], max_length=20, null=True),
        ),
    ]
